---
- name: Development enviroment setup
  hosts: localhost
  pre_tasks:
    - name: Set user home directory
      ansible.builtin.set_fact:
        user_home: "{{ lookup('env', 'HOME') }}"
      tags:
        - base
        - tools
        - fonts
        - symlinks

  roles:
    - role: base
      tags: base

    - role: tools
      tags: tools

    - role: fonts
      tags: fonts

    - role: symlinks
      tags: symlinks
