---
- name: Development enviroment setup
  hosts: localhost
  vars:
    user_home: "{{ lookup('env', 'HOME') }}"

  roles:
    - role: base
      tags: base

    - role: apps
      tags: apps

    - role: docker
      tags: docker

    - role: fonts
      tags: fonts

    - role: symlinks
      tags: symlinks

    - role: gnome
      tags: gnome

    - role: git
      tags: git
