---
- name: Create .gitconfig from template
  ansible.builtin.template:
    src: gitconfig.j2
    dest: "{{ user_home }}/.gitconfig"
    mode: "0644"

- name: Create .gitconfig-enki from template
  ansible.builtin.template:
    src: gitconfig-enki.j2
    dest: "{{ user_home }}/.gitconfig-enki"
    mode: "0644"

- name: Authenticate gh CLI (personal)
  ansible.builtin.shell: echo "{{ GH_TOKEN_PERSONAL }}" | gh auth login --with-token
  # no_log: true
  changed_when: true

- name: Authenticate gh CLI (work)
  ansible.builtin.shell: echo "{{ GH_TOKEN_WORK }}" | gh auth login --with-token
  # no_log: true
  changed_when: true
