[tools]
ansible-core = "latest"
atuin = "latest"
bitwarden = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
"github:latex-lsp/texlab" = "latest"
herdr = "latest"
jq = "latest"
lazygit = "latest"
lua-language-server = "latest"
neovim = "latest"
node = "lts"
"npm:@ansible/ansible-language-server" = "latest"
"npm:@fsouza/prettierd" = "latest"
"npm:pyright" = "latest"
pi = "latest"
"pypi:ansible-lint" = "latest"
ripgrep = "latest"
ruff = "latest"
shellcheck = "latest"
starship = "latest"
stylua = "latest"
uv = "latest"
zoxide = "latest"
