---
- name: Download WezTerm GPG key
  ansible.builtin.get_url:
    url: https://apt.fury.io/wez/gpg.key
    dest: /usr/share/keyrings/wezterm-fury.gpg.asc
    mode: "0644"
  become: true

- name: Convert GPG key to binary format
  ansible.builtin.command:
    cmd: gpg --yes --dearmor -o /usr/share/keyrings/wezterm-fury.gpg /usr/share/keyrings/wezterm-fury.gpg.asc
    creates: /usr/share/keyrings/wezterm-fury.gpg
  become: true

- name: Add WezTerm APT repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *"
    filename: wezterm
  become: true

- name: Install WezTerm
  ansible.builtin.apt:
    name: wezterm-nightly
    update_cache: true
  become: true
