---
- name: Download sh installers
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ user_home }}/.tmp/{{ item.name }}-install.sh"
    mode: "0644"
  loop:
    - name: uv
      url: https://astral.sh/uv/install.sh

    - name: direnv
      url: https://direnv.net/install.sh

    - name: starship
      url: https://starship.rs/install.sh

    - name: nvm
      url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh

    - name: rustup
      url: https://sh.rustup.rs

    - name: zoxide
      url: https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh
  loop_control:
    label: "{{ item.name }}"

- name: Install sh tools
  ansible.builtin.command:
    cmd: "sh {{ user_home }}/.tmp/{{ item.name }}-install.sh {{ item.args | default('') }}"
    creates: "{{ item.creates }}"
  loop:
    - name: uv
      creates: "{{ user_home }}/.local/bin/uv"

    - name: direnv
      creates: "{{ user_home }}/.local/bin/direnv"

    - name: starship
      creates: /usr/local/bin/starship
      args: "--yes"

    - name: nvm
      creates: "{{ user_home }}/.nvm/nvm.sh"

    - name: rustup
      creates: "{{ user_home }}/.cargo/bin/cargo"
      args: "-y --no-modify-path"

    - name: zoxide
      creates: "{{ user_home }}/.local/bin/zoxide"
  loop_control:
    label: "{{ item.name }}"
