#!/usr/bin/env python3

"""Renders markdown files in terminal"""

import sys
from rich.console import Console
from rich.markdown import Markdown

with open(sys.argv[1]) as f:
    Console().print(Markdown(f.read(), justify="left"))
