---
- name: Create Hack Nerd Font directory
  ansible.builtin.file:
    path: "{{ user_home }}/.local/share/fonts/Hack"
    state: directory
    mode: "0755"

- name: Install Hack Nerd Font
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/Hack.zip
    dest: "{{ user_home }}/.local/share/fonts/Hack"
    remote_src: true
    creates: "{{ user_home }}/.local/share/fonts/Hack/HackNerdFont-Regular.ttf"
  register: hack_nerd_font

- name: Refresh font cache
  ansible.builtin.command:
    cmd: fc-cache -f
  when: hack_nerd_font.changed
  changed_when: true
